services:
  postgres:
    #À adapter avec le nom du projet
    container_name: postgres-my-local-trip-back
    image: postgres
    environment:
      #À mettre dans le fichier .env
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      #À adapter avec le nom du projet
      POSTGRES_DB: my_local_trip_back
      volumes:
        -postgres:/data/postgres
      ports:
        #public:container
        -5432:5432
      networks:
        #À adapter avec le nom du projet
        -my-local-trip-back
      restart: unless-stopped
  mail-dev:
    #À adapter avec le nom du projet
    container_name: mail-my-local-trip-back
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
      #À adapter avec le nom du projet
  my-local-trip-back:
    driver: bridge

volumes:
  postgres:
    driver: local
