spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SPRING_EMAIL_HOST}
    port: ${SPRING_EMAIL_PORT}
    username: ${SPRING_EMAIL_USERNAME}
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timout: 3000
      writetimeout: 5000
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
server:
  port: 8088
  T